musashi_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50


  # Position Controllers ---------------------------------------
  back_left_wheel_shaft_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_link_to_back_left_wheel_shaft
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  back_right_wheel_shaft_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_link_to_back_right_wheel_shaft
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  front_left_wheel_shaft_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_link_to_front_left_wheel_shaft
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  front_right_wheel_shaft_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_link_to_front_right_wheel_shaft
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  # Velocity Controllers ---------------------------------------
  back_left_wheel_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: back_left_wheel_shaft_to_back_left_wheel
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  back_right_wheel_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: back_right_wheel_shaft_to_back_right_wheel
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  front_left_wheel_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: front_left_wheel_shaft_to_front_left_wheel
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  front_right_wheel_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: front_right_wheel_shaft_to_front_right_wheel
    pid: {p: 1000.0, i: 0.01, d: 10.0}
#  back_left_wheel_shaft_velocity_controller:
#    type: velocity_controllers/JointVelocityController
#    joint: base_link_to_back_left_wheel_shaft
#    pid: {p: 100.0, i: 0.01, d: 10.0}
#  back_right_wheel_shaft_velocity_controller:
#    type: velocity_controllers/JointVelocityController
#    joint: base_link_to_back_right_wheel_shaft
#    pid: {p: 100.0, i: 0.01, d: 10.0}
#  front_left_wheel_shaft_velocity_controller:
#    type: velocity_controllers/JointVelocityController
#    joint: base_link_to_front_left_wheel_shaft
#    pid: {p: 100.0, i: 0.01, d: 10.0}
#  front_right_wheel_shaft_velocity_controller:
#    type: velocity_controllers/JointVelocityController
#    joint: base_link_to_front_right_wheel_shaft
#    pid: {p: 100.0, i: 0.01, d: 10.0}

# robot disappears
#musashi_robot/gazebo_ros_control/pid_gains/back_left_wheel_shaft_to_back_left_wheel: {p: 100.0, i: 0.01, d: 10.0}
