//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the control package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __control__CONTROLGAINSCONFIG_H__
#define __control__CONTROLGAINSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace control
{
  class ControlGainsConfigStatics;

  class ControlGainsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(ControlGainsConfig &config, const ControlGainsConfig &max, const ControlGainsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const ControlGainsConfig &config1, const ControlGainsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, ControlGainsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const ControlGainsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ControlGainsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const ControlGainsConfig &config) const = 0;
      virtual void getValue(const ControlGainsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T ControlGainsConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T ControlGainsConfig::* field;

      virtual void clamp(ControlGainsConfig &config, const ControlGainsConfig &max, const ControlGainsConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const ControlGainsConfig &config1, const ControlGainsConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, ControlGainsConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const ControlGainsConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ControlGainsConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const ControlGainsConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const ControlGainsConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, ControlGainsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, ControlGainsConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<ControlGainsConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(ControlGainsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("vel_fl_k_p"==(*_i)->name){vel_fl_k_p = boost::any_cast<double>(val);}
        if("vel_fr_k_p"==(*_i)->name){vel_fr_k_p = boost::any_cast<double>(val);}
        if("vel_bl_k_p"==(*_i)->name){vel_bl_k_p = boost::any_cast<double>(val);}
        if("vel_br_k_p"==(*_i)->name){vel_br_k_p = boost::any_cast<double>(val);}
        if("vel_fl_k_i"==(*_i)->name){vel_fl_k_i = boost::any_cast<double>(val);}
        if("vel_fr_k_i"==(*_i)->name){vel_fr_k_i = boost::any_cast<double>(val);}
        if("vel_bl_k_i"==(*_i)->name){vel_bl_k_i = boost::any_cast<double>(val);}
        if("vel_br_k_i"==(*_i)->name){vel_br_k_i = boost::any_cast<double>(val);}
        if("steer_fl_k_p"==(*_i)->name){steer_fl_k_p = boost::any_cast<double>(val);}
        if("steer_fr_k_p"==(*_i)->name){steer_fr_k_p = boost::any_cast<double>(val);}
        if("steer_bl_k_p"==(*_i)->name){steer_bl_k_p = boost::any_cast<double>(val);}
        if("steer_br_k_p"==(*_i)->name){steer_br_k_p = boost::any_cast<double>(val);}
        if("steer_fl_k_i"==(*_i)->name){steer_fl_k_i = boost::any_cast<double>(val);}
        if("steer_fr_k_i"==(*_i)->name){steer_fr_k_i = boost::any_cast<double>(val);}
        if("steer_bl_k_i"==(*_i)->name){steer_bl_k_i = boost::any_cast<double>(val);}
        if("steer_br_k_i"==(*_i)->name){steer_br_k_i = boost::any_cast<double>(val);}
      }
    }

    double vel_fl_k_p;
double vel_fr_k_p;
double vel_bl_k_p;
double vel_br_k_p;
double vel_fl_k_i;
double vel_fr_k_i;
double vel_bl_k_i;
double vel_br_k_i;
double steer_fl_k_p;
double steer_fr_k_p;
double steer_bl_k_p;
double steer_br_k_p;
double steer_fl_k_i;
double steer_fr_k_i;
double steer_bl_k_i;
double steer_br_k_i;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_fl_k_p;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_fr_k_p;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_bl_k_p;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_br_k_p;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_fl_k_i;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_fr_k_i;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_bl_k_i;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_br_k_i;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double steer_fl_k_p;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double steer_fr_k_p;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double steer_bl_k_p;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double steer_br_k_p;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double steer_fl_k_i;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double steer_fr_k_i;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double steer_bl_k_i;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double steer_br_k_i;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("ControlGainsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const ControlGainsConfig &__max__ = __getMax__();
      const ControlGainsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const ControlGainsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const ControlGainsConfig &__getDefault__();
    static const ControlGainsConfig &__getMax__();
    static const ControlGainsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const ControlGainsConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void ControlGainsConfig::ParamDescription<std::string>::clamp(ControlGainsConfig &config, const ControlGainsConfig &max, const ControlGainsConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class ControlGainsConfigStatics
  {
    friend class ControlGainsConfig;

    ControlGainsConfigStatics()
    {
ControlGainsConfig::GroupDescription<ControlGainsConfig::DEFAULT, ControlGainsConfig> Default("Default", "", 0, 0, true, &ControlGainsConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_fl_k_p = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_fl_k_p = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_fl_k_p = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("vel_fl_k_p", "double", 0, "Proportional gain of the front left driving wheel.", "", &ControlGainsConfig::vel_fl_k_p)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("vel_fl_k_p", "double", 0, "Proportional gain of the front left driving wheel.", "", &ControlGainsConfig::vel_fl_k_p)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_fr_k_p = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_fr_k_p = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_fr_k_p = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("vel_fr_k_p", "double", 0, "Proportional gain of the front right driving wheel.", "", &ControlGainsConfig::vel_fr_k_p)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("vel_fr_k_p", "double", 0, "Proportional gain of the front right driving wheel.", "", &ControlGainsConfig::vel_fr_k_p)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_bl_k_p = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_bl_k_p = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_bl_k_p = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("vel_bl_k_p", "double", 0, "Proportional gain of the back left driving wheel.", "", &ControlGainsConfig::vel_bl_k_p)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("vel_bl_k_p", "double", 0, "Proportional gain of the back left driving wheel.", "", &ControlGainsConfig::vel_bl_k_p)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_br_k_p = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_br_k_p = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_br_k_p = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("vel_br_k_p", "double", 0, "Proportional gain of the back right driving wheel.", "", &ControlGainsConfig::vel_br_k_p)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("vel_br_k_p", "double", 0, "Proportional gain of the back right driving wheel.", "", &ControlGainsConfig::vel_br_k_p)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_fl_k_i = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_fl_k_i = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_fl_k_i = 0.01;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("vel_fl_k_i", "double", 0, "Integral gain of the front left driving wheel.", "", &ControlGainsConfig::vel_fl_k_i)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("vel_fl_k_i", "double", 0, "Integral gain of the front left driving wheel.", "", &ControlGainsConfig::vel_fl_k_i)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_fr_k_i = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_fr_k_i = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_fr_k_i = 0.01;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("vel_fr_k_i", "double", 0, "Integral gain of the front right driving wheel.", "", &ControlGainsConfig::vel_fr_k_i)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("vel_fr_k_i", "double", 0, "Integral gain of the front right driving wheel.", "", &ControlGainsConfig::vel_fr_k_i)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_bl_k_i = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_bl_k_i = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_bl_k_i = 0.01;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("vel_bl_k_i", "double", 0, "Integral gain of the back left driving wheel.", "", &ControlGainsConfig::vel_bl_k_i)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("vel_bl_k_i", "double", 0, "Integral gain of the back left driving wheel.", "", &ControlGainsConfig::vel_bl_k_i)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_br_k_i = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_br_k_i = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_br_k_i = 0.01;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("vel_br_k_i", "double", 0, "Integral gain of the back right driving wheel.", "", &ControlGainsConfig::vel_br_k_i)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("vel_br_k_i", "double", 0, "Integral gain of the back right driving wheel.", "", &ControlGainsConfig::vel_br_k_i)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.steer_fl_k_p = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.steer_fl_k_p = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.steer_fl_k_p = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("steer_fl_k_p", "double", 0, "Proportional gain of the front left steering wheel.", "", &ControlGainsConfig::steer_fl_k_p)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("steer_fl_k_p", "double", 0, "Proportional gain of the front left steering wheel.", "", &ControlGainsConfig::steer_fl_k_p)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.steer_fr_k_p = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.steer_fr_k_p = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.steer_fr_k_p = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("steer_fr_k_p", "double", 0, "Proportional gain of the front right steering wheel.", "", &ControlGainsConfig::steer_fr_k_p)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("steer_fr_k_p", "double", 0, "Proportional gain of the front right steering wheel.", "", &ControlGainsConfig::steer_fr_k_p)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.steer_bl_k_p = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.steer_bl_k_p = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.steer_bl_k_p = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("steer_bl_k_p", "double", 0, "Proportional gain of the back left steering wheel.", "", &ControlGainsConfig::steer_bl_k_p)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("steer_bl_k_p", "double", 0, "Proportional gain of the back left steering wheel.", "", &ControlGainsConfig::steer_bl_k_p)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.steer_br_k_p = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.steer_br_k_p = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.steer_br_k_p = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("steer_br_k_p", "double", 0, "Proportional gain of the back right steering wheel.", "", &ControlGainsConfig::steer_br_k_p)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("steer_br_k_p", "double", 0, "Proportional gain of the back right steering wheel.", "", &ControlGainsConfig::steer_br_k_p)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.steer_fl_k_i = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.steer_fl_k_i = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.steer_fl_k_i = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("steer_fl_k_i", "double", 0, "Integral gain of the front left steering wheel.", "", &ControlGainsConfig::steer_fl_k_i)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("steer_fl_k_i", "double", 0, "Integral gain of the front left steering wheel.", "", &ControlGainsConfig::steer_fl_k_i)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.steer_fr_k_i = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.steer_fr_k_i = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.steer_fr_k_i = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("steer_fr_k_i", "double", 0, "Integral gain of the front right steering wheel.", "", &ControlGainsConfig::steer_fr_k_i)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("steer_fr_k_i", "double", 0, "Integral gain of the front right steering wheel.", "", &ControlGainsConfig::steer_fr_k_i)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.steer_bl_k_i = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.steer_bl_k_i = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.steer_bl_k_i = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("steer_bl_k_i", "double", 0, "Integral gain of the back left steering wheel.", "", &ControlGainsConfig::steer_bl_k_i)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("steer_bl_k_i", "double", 0, "Integral gain of the back left steering wheel.", "", &ControlGainsConfig::steer_bl_k_i)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.steer_br_k_i = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.steer_br_k_i = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.steer_br_k_i = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("steer_br_k_i", "double", 0, "Integral gain of the back right steering wheel.", "", &ControlGainsConfig::steer_br_k_i)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ControlGainsConfig::AbstractParamDescriptionConstPtr(new ControlGainsConfig::ParamDescription<double>("steer_br_k_i", "double", 0, "Integral gain of the back right steering wheel.", "", &ControlGainsConfig::steer_br_k_i)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ControlGainsConfig::AbstractGroupDescriptionConstPtr(new ControlGainsConfig::GroupDescription<ControlGainsConfig::DEFAULT, ControlGainsConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<ControlGainsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<ControlGainsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<ControlGainsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    ControlGainsConfig __max__;
    ControlGainsConfig __min__;
    ControlGainsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const ControlGainsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static ControlGainsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &ControlGainsConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const ControlGainsConfig &ControlGainsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const ControlGainsConfig &ControlGainsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const ControlGainsConfig &ControlGainsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<ControlGainsConfig::AbstractParamDescriptionConstPtr> &ControlGainsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<ControlGainsConfig::AbstractGroupDescriptionConstPtr> &ControlGainsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const ControlGainsConfigStatics *ControlGainsConfig::__get_statics__()
  {
    const static ControlGainsConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = ControlGainsConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __CONTROLGAINSRECONFIGURATOR_H__
