(cl:defpackage sdv_msgs-msg
  (:use )
  (:export
   "<CONTROLREFERENCE>"
   "CONTROLREFERENCE"
   "<CONTROLREFERENCE>"
   "CONTROLREFERENCE"
   "<TRAJECTORY>"
   "TRAJECTORY"
   "<TRAJECTORY>"
   "TRAJECTORY"
   "<TRAJECTORYPOINT>"
   "TRAJECTORYPOINT"
   "<TRAJECTORYPOINT>"
   "TRAJECTORYPOINT"
  ))

