(cl:in-package sdv_msgs-msg)
(cl:export '(VELOCITY_REF_FRONT_LEFT-VAL
          VELOCITY_REF_FRONT_LEFT
          VELOCITY_REF_FRONT_RIGHT-VAL
          VELOCITY_REF_FRONT_RIGHT
          VELOCITY_REF_BACK_LEFT-VAL
          VELOCITY_REF_BACK_LEFT
          VELOCITY_REF_BACK_RIGHT-VAL
          VELOCITY_REF_BACK_RIGHT
          STEERING_REF_FRONT_LEFT-VAL
          STEERING_REF_FRONT_LEFT
          STEERING_REF_FRONT_RIGHT-VAL
          STEERING_REF_FRONT_RIGHT
          STEERING_REF_BACK_LEFT-VAL
          STEERING_REF_BACK_LEFT
          STEERING_REF_BACK_RIGHT-VAL
          STEERING_REF_BACK_RIGHT
          STOP_MOTORS-VAL
          STOP_MOTORS
))