costmap:
  global_frame: /odom

  update_frequency: 15.0
  publish_frequency: 10.0
  rolling_window: true
  track_unknown_space: false
  footprint_clearing_enabled: false

  width: 16
  height: 16
  resolution: 0.05
  origin_x: -8
  origin_y: -8

  plugins:
    - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
    - {name: sonar, type: "range_sensor_layer::RangeSensorLayer"}
    - {name: inflation, type: "costmap_2d::InflationLayer"}
