#left and right wheel velocities (already transformed in robot values)
int32 left_wheel_cmd
int32 right_wheel_cmd
float32 sampling_time
---
#result definition (send a boolean if sending signal was succesfull)
bool success
---
#feedback (currently not needed)
int32 foo
