// Generated by gencpp from file industrial_robot_qt/RobotWheelVel.msg
// DO NOT EDIT!


#ifndef INDUSTRIAL_ROBOT_QT_MESSAGE_ROBOTWHEELVEL_H
#define INDUSTRIAL_ROBOT_QT_MESSAGE_ROBOTWHEELVEL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace industrial_robot_qt
{
template <class ContainerAllocator>
struct RobotWheelVel_
{
  typedef RobotWheelVel_<ContainerAllocator> Type;

  RobotWheelVel_()
    : left_wheel(0)
    , right_wheel(0)  {
    }
  RobotWheelVel_(const ContainerAllocator& _alloc)
    : left_wheel(0)
    , right_wheel(0)  {
  (void)_alloc;
    }



   typedef int32_t _left_wheel_type;
  _left_wheel_type left_wheel;

   typedef int32_t _right_wheel_type;
  _right_wheel_type right_wheel;





  typedef boost::shared_ptr< ::industrial_robot_qt::RobotWheelVel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::industrial_robot_qt::RobotWheelVel_<ContainerAllocator> const> ConstPtr;

}; // struct RobotWheelVel_

typedef ::industrial_robot_qt::RobotWheelVel_<std::allocator<void> > RobotWheelVel;

typedef boost::shared_ptr< ::industrial_robot_qt::RobotWheelVel > RobotWheelVelPtr;
typedef boost::shared_ptr< ::industrial_robot_qt::RobotWheelVel const> RobotWheelVelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::industrial_robot_qt::RobotWheelVel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::industrial_robot_qt::RobotWheelVel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::industrial_robot_qt::RobotWheelVel_<ContainerAllocator1> & lhs, const ::industrial_robot_qt::RobotWheelVel_<ContainerAllocator2> & rhs)
{
  return lhs.left_wheel == rhs.left_wheel &&
    lhs.right_wheel == rhs.right_wheel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::industrial_robot_qt::RobotWheelVel_<ContainerAllocator1> & lhs, const ::industrial_robot_qt::RobotWheelVel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace industrial_robot_qt

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::industrial_robot_qt::RobotWheelVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::industrial_robot_qt::RobotWheelVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::industrial_robot_qt::RobotWheelVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::industrial_robot_qt::RobotWheelVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::industrial_robot_qt::RobotWheelVel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::industrial_robot_qt::RobotWheelVel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::industrial_robot_qt::RobotWheelVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3cad0bda4aa523fe6ab3c0809a84e390";
  }

  static const char* value(const ::industrial_robot_qt::RobotWheelVel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3cad0bda4aa523feULL;
  static const uint64_t static_value2 = 0x6ab3c0809a84e390ULL;
};

template<class ContainerAllocator>
struct DataType< ::industrial_robot_qt::RobotWheelVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "industrial_robot_qt/RobotWheelVel";
  }

  static const char* value(const ::industrial_robot_qt::RobotWheelVel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::industrial_robot_qt::RobotWheelVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 left_wheel\n"
"int32 right_wheel\n"
;
  }

  static const char* value(const ::industrial_robot_qt::RobotWheelVel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::industrial_robot_qt::RobotWheelVel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_wheel);
      stream.next(m.right_wheel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotWheelVel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::industrial_robot_qt::RobotWheelVel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::industrial_robot_qt::RobotWheelVel_<ContainerAllocator>& v)
  {
    s << indent << "left_wheel: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left_wheel);
    s << indent << "right_wheel: ";
    Printer<int32_t>::stream(s, indent + "  ", v.right_wheel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INDUSTRIAL_ROBOT_QT_MESSAGE_ROBOTWHEELVEL_H
